export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_SHIRT_FILTER = 'SET_SHIRT_FILTER';
export const SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
